version: '2'

services:
    nginx:
        image: nginx:1.25.1
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build: ./docker/php/
        volumes:
            - .:/var/www/html
